@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Component "DiscountService" {
  + calculateDiscount(userId) : double
  + applyDiscount(orderId, discountAmount) : void
}
Component "UserProfileService" {
  + getUserCategory(userId) : UserCategory
} 

@enduml